name: build-pack-publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Add private GitHub registry to NuGet
      run: dotnet nuget add source https://nuget.pkg.github.com/drsmile1001/index.json  --name "github" --username drsmile1001 --password ${{ secrets.GITHUB_TOKEN }}  --store-password-in-clear-text

    - name: Pack
      run: dotnet pack -c Release -o out

    - name: Push generated package to GitHub registry
      run: dotnet nuget push out/*.nupkg --source "github" --skip-duplicate
      